[package]
name = "relay_control"
version = "0.2.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
env_logger = "0.9"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serialport = "4.0"
structopt = "0.3"
toml = "0.5"

